NAME := swcloudtv

BUILD_TARGET_TYPE := static

BINDIR := $(ROOTDIR)/out/libs/swcloudtv

SRC += swcloudtv.c 

INCDIR = -I. \
-I$(SWMODULESROOT)/pub/include \
-I$(SWAPIROOT)/pub/base/include					


include $(SWAPIROOT)/build/common.Makefile
